export const ADD_WORKOUT = "ADD_WORKOUT";

export const DELETE_WORKOUT = "DELETE_WORKOUT";

export const ADD_EXERCISE_TO_WORKOUT = "ADD_EXERCISE_TO_WORKOUT";

export const SELECT_WORKOUT = "SELECT_WORKOUT";

export const DELETE_EXERCISE_FROM_WORKOUT = "DELETE_EXERCISE_FROM_WORKOUT";
